# Generated by Django 4.0.2 on 2022-06-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
